config/routes.rb
Rails.application.routes.draw do
  

  root "site#home"

  get '/sign_up', to: 'users#new', as: :sign_up
  get '/profile', to: 'users#show', as: :profile
  get '/login', to: 'sessions#new', as: :new_login
  post '/login', to: 'sessions#create', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout
resources :users, only: [:create, :edit, :update, :destroy]
resources :sessions, only: [:create]
resources :posts
end

  

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #login form
  def new

  end

  #authenticate the user
  def create  
    user = User.find_by_email(user_params[:email])

    if user.authenticate(user_params[:password])
        sessions[:user_id] = user.id 
        redirect_to user_path
    else
      puts "didn't authenticate"
      redirect_to new_user_path
    end

  end

  #logout user
  def destroy
    sessions[:user_id] = nil    
    redirect_to "/"
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :first_name, :last_name)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to '/profile'
  end

  def edit
    @current_user = User.find(session[:user_id])
  end

  def update
    @current_user = User.find(session[:user_id])
    @current_user.update_attributes user_params
    redirect_to '/profile'
  end

  def show
    @current_user = User.find(session[:user_id])
  end

  def destroy
    @current_user = User.find(session[:user_id])
    User.delete(@current_user.id)
    redirect_to '/'
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stories</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/site/about.html.erb
<h1>About</h1>

app/views/site/home.html.erb
<nav>
  <%= link_to 'Sign Up', sign_up_path %>
  <%= link_to 'Login', login_path %>

</nav>

<h1>Dev Stories</h1>
<blockquote>"share your dev stories"</blockquote>

app/views/users/edit.html.erb
<h1>Edit <%= @current_user.first_name %></h1>

<%= form_for @current_user do |f| %>
  <%= f.label :first_name %>:
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %>:
  <%= f.text_field :last_name %><br>

  <%= f.label :email %>:
  <%= f.text_field :email %><br>

  <%= f.label :password %>:
  <%= f.text_field :password %><br>

  <%= f.submit "Submit"%>
<% end %>

app/views/users/index.html.erb
<h1>Sign Up</h1>
<hr>

<% @users.each do |u| %>
<div>
  Id: <%= u.id %><br>
  Email: <%= u.email %><br>
  First Name:<%= u.first_name %> <br>
  Last Name:<%= u.last_name %><br>
  <%= button_to "show", "/users/#{u.id}", method: "get"%>
  </div>
  <hr>
 <% end %>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>:
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %>:
  <%= f.text_field :last_name %><br>

  <%= f.label :email %>:
  <%= f.text_field :email %><br>

  <%= f.label :password %>:
  <%= f.text_field :password %><br>

  <%= f.submit "Submit"%>
<% end %>

app/views/users/show.html.erb
<div>
 First Name: <%= @current_user.first_name %><br>
 Last Name: <%= @current_user.last_name %><br>
 <%= link_to "edit", "/users/#{@current_user.id}/edit" %>

  <%= button_to "delete", "/users/#{@current_user.id}", method: :delete%>

 </div>